### ISSUE TITLE
Seems it's broken

### ISSUE THREAD

**Issue by ionelmc** [pytest-dev/plugincompat#12]
Few plugins fail now with peculiar errors like:

```
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.9/bin/tox", line 9, in <module>
    load_entry_point('tox==1.8.2.dev1', 'console_scripts', 'tox')()
  File "/home/travis/virtualenv/python2.7.9/src/tox/tox/_cmdline.py", line 25, in main
    config = parseconfig(args, 'tox')
  File "/home/travis/virtualenv/python2.7.9/src/tox/tox/_config.py", line 42, in parseconfig
    parseini(config, inipath)
  File "/home/travis/virtualenv/python2.7.9/src/tox/tox/_config.py", line 299, in __init__
    self._makeenvconfig(name, section, reader._subs, config)
  File "/home/travis/virtualenv/python2.7.9/src/tox/tox/_config.py", line 374, in _makeenvconfig
    name = self._replace_forced_dep(name, config)
  File "/home/travis/virtualenv/python2.7.9/src/tox/tox/_config.py", line 432, in _replace_forced_dep
    if self._is_same_dep(forced_dep, name):
  File "/home/travis/virtualenv/python2.7.9/src/tox/tox/_config.py", line 443, in _is_same_dep
    dep2_name = pkg_resources.Requirement.parse(dep2).project_name
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/pkg_resources.py", line 2745, in parse
    reqs = list(parse_requirements(s))
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/pkg_resources.py", line 2678, in parse_requirements
    "version spec")
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/pkg_resources.py", line 2645, in scan_list
    raise ValueError(msg, line, "at", line[p:])
ValueError: ('Expected version spec in', '-r/home/travis/build/nicoddemus/pytest-plugs/.work/pytest-splinter-1.2.7/requirements-testing.txt', 'at', '/home/travis/build/nicoddemus/pytest-plugs/.work/pytest-splinter-1.2.7/requirements-testing.txt')


Time: 0.5 seconds
```

Examples:

http://pytest-plugs.herokuapp.com/output/pytest-splinter-1.2.7?py=py27&pytest=2.6.4
http://pytest-plugs.herokuapp.com/output/pytest-benchmark-1.1.0?py=py27&pytest=2.6.4
http://pytest-plugs.herokuapp.com/output/pytest-config-0.0.11?py=py27&pytest=2.6.4

**Comment by nicoddemus** [comment]
Hey,

I did take a look at the problem, but it seems the solution is more complicated than I thought, seems to be a problem on how tox handles the `--force-dep` option. This might take awhile. 

Thanks again for the report! :smile:

**Comment by ionelmc** [comment]
Can you elaborate on what's the problem? `--force-dep` doesn't seem related to that weird error about `requirements.txt`

**Comment by nicoddemus** [comment]
Sure! :smile:

From the stack trace:

```
File "/home/travis/virtualenv/python2.7.9/src/tox/tox/_config.py", line 374, in _makeenvconfig
    name = self._replace_forced_dep(name, config)
  File "/home/travis/virtualenv/python2.7.9/src/tox/tox/_config.py", line 432, in _replace_forced_dep
    if self._is_same_dep(forced_dep, name):
  File "/home/travis/virtualenv/python2.7.9/src/tox/tox/_config.py", line 443, in _is_same_dep
    dep2_name = pkg_resources.Requirement.parse(dep2).project_name
```

The problem lies in constructing the `pkg_resources.Requirement.parse` object, which is used when the `--force-dep` option is passed. This happens when a plugin lists its dependencies using a `requirements.txt` file like this: 

```ini
[testenv]
deps = -r{toxinidir}/requirements-testing.txt
```

Instead of defining them explicitly:

```ini
[testenv]
deps = foo==1.0
   bar>1.2
```

In this case `"-r /path/to/requirements.txt"` is being passed instead of a project version requirement to `pkg_resources.Requirement.parse`. I didn't looked in the problem too deeply, but it seems like `tox` in the normal workflow just forwards `deps` to `pip install` machinery, but when the `--force-dep` option is passed it actually tries to parse dependencies to find the one to substitute versions and breaks. And that is my fault as I wrote support for `--force-dep`. :smile:

The correct solution would be to parse the requirements (using `pkg_resources`), but hadn't have time to look at it yet as I was on vacation. But I will try to get to this next week. 

Cheers,
