### ISSUE TITLE
update_index.py fails when plugin doesn't publish any release

### ISSUE THREAD

**Issue by lukas-bednar** [pytest-dev/plugincompat#21]
bellow you can find error with simple debug print, where is displayed name of plugin and list or releases.
you can see that ``pytest-voluptuous`` did hide releases, and it made this script to fail on InxexError.

```
$ python update_index.py 
pytest-falcon ['0.4.2']
pytest-regtest ['0.15.0']
pytest-param ['0.1.1']
pytest-voluptuous []
Traceback (most recent call last):
  File "update_index.py", line 109, in <module>
    main()
  File "update_index.py", line 100, in main
    plugins = sorted(iter_plugins(client))
  File "update_index.py", line 48, in iter_plugins
    names_and_versions[name] = sorted(versions, key=LooseVersion)[0]
IndexError: list index out of range
```

**Comment by nicoddemus** [comment]
Fixed by #22
